Refactor all tasks to use filepath inputs (#149)
* Try overide prefect task deco so args become name

As args passed at runtime in `run` method need to
override automatically-set task name which is name
of func in `run` method...

* Refactor all etl tasks to io filepaths

Now every task in residential etl takes a filepath input,
performs some operation & saves the result in an output
filepath.  This means that each task doesn't depend on
global state and so can be run individually if required -
run flow to generate data and can then play with the tasks
independent of flow context...

Also mocks out DATA_DIR for FTEST_DATA_DIR instead of passing
it as a flow parameter (to residential etl) as this produces a
cleaner etl visualization.  Previously the external_dir prefect
parameter was split in the viz into a number of Div bubbles rendering
the etl viz into a dependency hell mess.  Now each filepath input
appears in the viz as independent to all others and so the dependency
mess problem is eliminated...

* Add refactored zip utility

Forgot to commit last time...

* Blacken code...

* Update dependencies

* Debug build as pytest failing

in test_elec_diversity_curve due to:
```python
pyarrow.lib.ArrowKeyError: A type extension with name pandas.period already defined
```

which only fails in CI

* Remove tmate debug session

ssh into CI & pytest ran as in local without
failure. Weird...

* Change fixture to from pq to dask dataframe

`to.parquet` failed when pytest is parallelised as
can't register pandas.dot twice in pyarrow rn...
Skipping parquet dependency resolves bug

* BUG: forgot to change local func variable name