Debug build as pytest failing
in test_elec_diversity_curve due to:
```python
pyarrow.lib.ArrowKeyError: A type extension with name pandas.period already defined
```

which only fails in CI